name: Build MacOS

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        cpp_compiler: [g++-11, clang++-13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CMake
      run: brew install cmake

    - name: Install g++-11
      if: matrix.cpp_compiler == 'g++-11'
      run: |
        brew install gcc@11
        echo "export PATH=\"$(brew --prefix gcc@11)/bin:$PATH\"" >> $GITHUB_ENV

    - name: Setup MacPorts and install clang++-13
      if: matrix.cpp_compiler == 'clang++-13'
      uses: melusina-org/gha-install-macports@v1
      with:
        ports: clang-13
      
  

    - name: Set reusable strings
      id: strings
      shell: bash
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure ADOL-C
      if: matrix.cpp_compiler == 'clang++13'
      shell: bash
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -DCMAKE_C_COMPILER=/opt/local/bin/clang-mp-13 \
        -DCMAKE_CXX_COMPILER=/opt/local/bin/clang++-mp-13 \
        -DCMAKE_CXX_FLAGS="-stdlib=libc++ -I/opt/local/libexec/llvm-13/include/c++/v1" \
        -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++ -L/opt/local/libexec/llvm-13/lib -Wl,-rpath,/opt/local/libexec/llvm-13/lib" \
        -S ${{ github.workspace }}


    - name: Configure ADOL-C
      if: matrix.cpp_compiler == 'g++-11'
      shell: bash
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -DCMAKE_C_COMPILER=gcc-11 \
        -DCMAKE_CXX_COMPILER=g++-11 \
        -S ${{ github.workspace }}

    - name: Build ADOL-C
      run: >
        cmake 
        --build ${{ steps.strings.outputs.build-output-dir }} 
        --config ${{ matrix.build_type }}

