name: Tests with Sanitizers
on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
    
jobs: 
  run-tests-with-sanitizers: 
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix: 
        sanitizer: [address, undefined, thread, memory]
        build_type: [Debug]
        c_compiler : [clang]
        cpp_compiler: [clang++]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang libboost-all-dev

      - name: Configure CMake
        run: |
          SANITIZER_FLAGS="-fsanitize=${{ matrix.sanitizer }} -fno-omit-frame-pointer -g"
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_CXX_FLAGS=="${{ matrix.sanitizer_flags }}" \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
            -DCMAKE_C_FLAGS="$SANITIZER_FLAGS" \
            -DCMAKE_CXX_FLAGS="$SANITIZER_FLAGS" \
            -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Run tests
        run: |
          cd build && ctest -V
