
name: Run Tests (Release)
on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs: 
  run-tests: 
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix: 
        build_type: [Release]
        c_compiler: [gcc, clang]
        cpp_compiler: [g++, clang++]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y libboost-all-dev

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Run tests
        run: |
          cd build && ctest --output-on-failure
