
name: Run Tests
on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs: 
    run-tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Install Boost
          shell: bash
          run: |
            sudo apt-get install libboost-all-dev

        - name: Configure and build ADOL-C
          run: |
            mkdir build
            cd build
            cmake \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_BUILD_TYPE=Tests \
            -S .. \
            -B .
            cmake --build .
        
        - name: Run Tests
          run: ./build/ADOL-C/boost-test/boost-test-adolc


        